### ISSUE TITLE
[Question] Regarding live code editor

### ISSUE THREAD

**Issue by patricia-patricia** [rwth-acis/CAE#11]
I'm new to this project and have a question regarding the live code editor.
It doesn't seem NRT to me.
The code seems to only appear when pushed to github and can't be edited.
Is there something I do wrong?

**Comment by pdolif** [comment]
If I get your question right, then you're wondering why changes to the model do not directly affect the source code in NRT.
Yes, that is true. I think that the NRT just stands for the model editor and the live code editor separately. Because SyncMeta allows NRT collaborative modeling and on the other side the live code editor also allows collaborative NRT editing of the source code.

For editing the code, you first need to create a "manual-commit" which contains an initial model. After you created this commit, the source code is generated (and also pushed to GitHub). If you're user-role in the CAE allows to view the live code editor, then you should be able to see the live code editor widget. It has a menu which can be accessed on the top left of the widget and which allows to switch between the various files. The widget also allows to edit some parts of the code files. Once you're done with the changes, you can click on "Publish" and the changes should also be commited and pushed to GitHub automatically.

**Comment by patricia-patricia** [comment]
>  The widget also allows to edit some parts of the code files.

Unfortunately, I can't type anything. Is the editing limited?

**Comment by pdolif** [comment]
In general editing is not allowed in all parts of the source code. There are only some parts of some files where editing is allowed. I think that this is required to maintain the synchronization between the model and the source code.
You can test it as follows (if everything is working correctly):
- For a frontend component you should be able to edit the "applicationScript.js" inside the "js" folder as an example. There also the parts which are not editable have a grey background, while the parts that can be edited have a white background.
- For a microservice component you should also have some files in "src/main/i5/las2peer/services/..." where some parts are editable.

**Comment by patricia-patricia** [comment]
Yes. The parts you mention are editable. Thank you.
